### PR TITLE
fix(deps): migrate to @gitbeaker/rest

### LINKED ISSUE #131: Deprecated package gitbeaker/node
When installing there is a warning given by npm:
```
npm WARN deprecated @gitbeaker/node@35.8.1: Please use its successor @gitbeaker/rest
```

### PR DESCRIPTION
**Pull request by alan910127**
Closes #131 

## Summary

- Remove the usage of `@gitbeaker/node` and use `@gitbeaker/rest` instead.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -24,20 +24,29 @@ export const createApi = (gitlabToken?: string) => {
   }
 
   const token = gitlabToken || process.env.GITLAB_TOKEN
+  if (!token) {
+    throw new Error('GitLab token is not set')
+  }
```
Comment (alan910127) [inline src/index.ts:29]: I'm not sure if I should throw the error here. It seems like `@gitbeaker/node` accepts `undefined` as the token but it's not the case with `@gitbeaker/rest`.

File: package.json [hunk 2]
```diff
@@ -77,7 +77,7 @@
     "@changesets/parse": "^0.3.16",
     "@changesets/pre": "^1.0.14",
     "@changesets/read": "^0.5.9",
-    "@gitbeaker/node": "^35.7.0",
+    "@gitbeaker/rest": "^39.23.0",
```
Comment (JounQin) [inline package.json:80]: Thanks for your work first! It's realy a good start. Although this change should be marked as minor change instead of patch. It's a feature change instead of bug fix.

**Review by JounQin — CHANGES_REQUESTED** [review]

File: src/comment.ts [hunk 3]
```diff
@@ -129,17 +129,20 @@ const getNoteInfo = (api: Gitlab, mrIid: number | string) =>
...
-        /^\.changeset\/.+\.md$/.test(file.new_path) &&
-        file.new_path !== '.changeset/README.md',
-    ),
-  )
+const hasChangesetBeenAdded = async (
+  changedFilesPromise: ReturnType<MergeRequests['showChanges']>,
+) => {
+  const changedFiles = await changedFilesPromise
+  const changes =
+    'changes' in changedFiles ? changedFiles.changes : changedFiles.data.changes
```
Comment (JounQin) [inline src/comment.ts:137]: Hmm... Why there are two possible paths representing same thing?

File: src/index.ts (hunk 1 above)
Comment (JounQin) [reply src/index.ts:29]: `GITLAB_TOKEN` env is marked as required in README, so we can just assert `process.env.GITLAB_TOKEN` can never be nil here.

File: src/index.ts [hunk 4]
```diff
@@ -24,20 +24,29 @@ export const createApi = (gitlabToken?: string) => {
...
 
-  let tokenType: 'jobToken' | 'oauthToken' | 'token' = 'token'
+  const host = process.env.GITLAB_HOST ?? process.env.CI_SERVER_URL
 
+  // we cannot use { [tokenType]: token } now
```
Comment (JounQin) [inline src/index.ts:33]: It weird, can you show some related typing errors here?

File: src/utils.ts [hunk 5]
```diff
@@ -155,7 +155,9 @@ export const execSync = (command: string) =>
...
 
 export const getUsername = async (api: Gitlab) => {
-  return process.env.GITLAB_CI_USER_NAME == null
-    ? await api.Users.current().then(currentUser => currentUser.username)
-    : process.env.GITLAB_CI_USER_NAME
+  if (process.env.GITLAB_CI_USER_NAME != null) {
+    return process.env.GITLAB_CI_USER_NAME
+  }
+  const currentUser = await api.Users.showCurrentUser()
+  return currentUser.username
```
Comment (JounQin) [inline src/utils.ts:162]:
```suggestion
  return process.env.GITLAB_CI_USER_NAME || await api.Users.showCurrentUser().then(currentUser => currentUser.username)
```

I believe it's much cleaner personally.

**Review by JounQin — CHANGES_REQUESTED** [review]

**Comment by JounQin** [comment]
image

https://github.com/un-ts/changesets-gitlab/blob/a30d2babda63e0bd49ef3123671cc7c062ab663d/.codesandbox/ci.json#L2

https://github.com/un-ts/changesets-gitlab/blob/a30d2babda63e0bd49ef3123671cc7c062ab663d/.github/workflows/ci.yml#L13-L15

@alan910127 Please help to change these node versions at the same time.

For codesandbox, we can use 18, for GitHub Actions, we should use `18` and `20`

File: src/comment.ts (hunk 3 above)
Comment (alan910127) [reply src/comment.ts:137]: The `showChanges` function now is a generic function that may return `MergeRequestChangesSchema` or `ExpandedResponse<MergeRequestChangesSchema>` based on the input options. 

Even though we are not providing `{ showExpanded: true }` and the function defaults `E` to be `false`, it cannot be known by the type system if we use `ReturnType` to infer the type of that promise.

File: src/index.ts (hunk 4 above)
Comment (alan910127) [reply src/index.ts:33]: image

```
Argument of type '{ [x: string]: string | undefined; host: string | undefined; }' is not assignable to parameter of type 'BaseResourceOptions<false>'.
  Property 'jobToken' is missing in type '{ [x: string]: string | undefined; host: string | undefined; }' but required in type 'BaseRequestOptionsWithJobToken<false>'.
```

File: src/utils.ts (hunk 5 above)
Comment (alan910127) [reply src/utils.ts:162]: I believe that we do not need the `await` here since promises are automatically flattened. Am I correct?

**Comment by alan910127** [comment]
> image
> https://github.com/un-ts/changesets-gitlab/blob/a30d2babda63e0bd49ef3123671cc7c062ab663d/.codesandbox/ci.json#L2
> 
> https://github.com/un-ts/changesets-gitlab/blob/a30d2babda63e0bd49ef3123671cc7c062ab663d/.github/workflows/ci.yml#L13-L15
> 
> @alan910127 Please help to change these node versions at the same time.
> 
> For codesandbox, we can use 18, for GitHub Actions, we should use `18` and `20`

How about the release action in `.github/workflows/release.yml`? Should I also bump it to node 18?

File: package.json (hunk 2 above)
Comment (alan910127) [reply package.json:80]: Updated!

File: src/index.ts (hunk 1 above)
Comment (alan910127) [reply src/index.ts]: Would it be better if we export an `env` object from a module that has defined the "actual" type of the environment variables? I could open another PR to make this change afterward. 😄

**Comment by JounQin** [comment]
> How about the release action in .github/workflows/release.yml? Should I also bump it to node 18?

We can change to use `lts/*`

File: src/index.ts (hunk 1 above)
Comment (JounQin) [reply src/index.ts]: > Would it be better if we export an `env` object from a module that has defined the "actual" type of the environment variables? I could open another PR to make this change afterward. 😄

Sure!

File: src/comment.ts (hunk 3 above)
Comment (JounQin) [reply src/comment.ts:137]: OK, weird API design though.

File: .github/workflows/ci.yml [hunk 6]
```diff
@@ -9,10 +9,7 @@ jobs:
     name: Lint and Test with Node.js ${{ matrix.node }}
     strategy:
       matrix:
-        node:
-          - 14
-          - 16
-          - 18
+        node: [18, 20]
```
Comment (JounQin) [inline .github/workflows/ci.yml:12]: Please preserve the formatting style

File: .github/workflows/release.yml [hunk 7]
```diff
@@ -16,10 +16,10 @@ jobs:
           # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
           fetch-depth: 0
 
-      - name: Setup Node.js 16
+      - name: Setup Node.js 18
         uses: actions/setup-node@v3
         with:
-          node-version: 16
+          node-version: 18
```
Comment (JounQin) [inline .github/workflows/release.yml:22]:
```suggestion
      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
```

File: src/utils.ts [hunk 8]
```diff
@@ -155,7 +155,8 @@ export const execSync = (command: string) =>
 export const getOptionalInput = (name: string) => getInput(name) || undefined
 
 export const getUsername = async (api: Gitlab) => {
```
Comment (JounQin) [inline src/utils.ts:157]:
```suggestion
export const getUsername = (api: Gitlab) => {
```

Comment (alan910127) [reply src/utils.ts:157]: If the `async` is removed, the return type of this function becomes `string | Promise<string>`, is this acceptable?

File: .github/workflows/ci.yml (hunk 6 above)
Comment (alan910127) [reply .github/workflows/ci.yml:12]: Sure. However, it appears that some dependencies are not compatible with node.js 20. Is yarn default to set the `engines-strict` config flag?

File: src/utils.ts (hunk 8 above)
Comment (JounQin) [reply src/utils.ts:157]: I personally accept it, but if the linter complaints, `async` is also fine.

File: src/index.ts (hunk 4 above)
Comment (JounQin) [reply src/index.ts:29]: OK, weird but acceptable.

File: src/utils.ts (hunk 8 above)
Comment (alan910127) [reply src/utils.ts:157]: The linter is not complaining about it though, maybe I can just remove the `async`.

**Review by JounQin — APPROVED** [review]
