### PR TITLE
fix: Gitlab Host Fallbacks

### LINKED ISSUE #146: v0.11.1 includes breaking change for environment variables
The upgrade from 0.11.0 to 0.11.1 broke some environment variable usage.

For example, previously the host would fallback to `process.env.CI_SERVER_URL`, but with this latest update I receive 401 unauthorized because I rely on the built-in gitlab CI `CI_SERVER_URL` environment variable instead of the explicit `GITLAB_HOST` environment variable this CLI is looking for.

For more information on `CI_SERVER_URL` see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

### PR DESCRIPTION
**Pull request by vinnymac**
v0.11.1 introduced a bug with gitlab host fallbacks, when environment variables were moved to their own module. This change reintroduces the gitlab host fallbacks.

Without this, I receive 401s when I use Gitlab CI with the `changesets-gitlab` CLI.

Fixes #146

### CODE REVIEW

File: src/env.ts [hunk 1]
```diff
@@ -15,6 +15,7 @@ export const env = {
     process.env.GITLAB_CI_USER_EMAIL || 'gitlab[bot]@users.noreply.gitlab.com',
   GITLAB_COMMENT_TYPE: process.env.GITLAB_COMMENT_TYPE ?? 'discussion',
   DEBUG_GITLAB_CREDENTIAL: process.env.DEBUG_GITLAB_CREDENTIAL ?? 'false',
+  GITLAB_HOST: process.env.GITLAB_HOST ?? process.env.CI_SERVER_URL ?? 'https://gitlab.com',
```
Comment (JounQin) [inline src/env.ts:18]: Thanks for the pr first. Please move this line before `GITLAB_CI_USER_EMAIL` to sync order with README.

**Review by JounQin — CHANGES_REQUESTED** [review]

**Review by JounQin — APPROVED** [review]

**Comment by JounQin** [comment]
@vinnymac CI is still broken due to formatting issue.
